name: calendar
description: "Drug Manager Calendar"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - lib/images4projects/apple.png
  - lib/images4projects/google.png
  - lib/images4projects/jablko.jpeg