name: calendar
description: "Drug Manager Calendar"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  auto_route: ^9.2.2
  firebase_auth: ^5.3.3
  syncfusion_flutter_calendar: ^27.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

assets:
  - assets/images/google.png
  - assets/images/apple.png
